// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EmitProgress(arg1) {
  return window['go']['main']['App']['EmitProgress'](arg1);
}

export function FindVideoFiles(arg1) {
  return window['go']['main']['App']['FindVideoFiles'](arg1);
}

export function GetAvailableCodecs() {
  return window['go']['main']['App']['GetAvailableCodecs']();
}

export function ProcessVideo(arg1) {
  return window['go']['main']['App']['ProcessVideo'](arg1);
}

export function ProcessVideoPaths(arg1) {
  return window['go']['main']['App']['ProcessVideoPaths'](arg1);
}

export function ShowNotification(arg1, arg2) {
  return window['go']['main']['App']['ShowNotification'](arg1, arg2);
}

export function StartEncodingWithOptions(arg1, arg2) {
  return window['go']['main']['App']['StartEncodingWithOptions'](arg1, arg2);
}
